[workspace]
resolver = "2"
members = [
    "crates/core",
    "crates/ecs",
    "crates/scheduler",
    "crates/render",
    "crates/platform",
    "crates/math",
    "crates/app",
]

[workspace.package]
version = "0.3.0"
