<<<<<<< HEAD
[package]
name = "rustgine"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
env_logger = "0.10.0"
log = "0.4"
winit = "0.30.12"
wgpu = "28.0.0"
pollster = "0.4.0"
=======
[workspace]
resolver = "2"
members = [
    "crates/core",
    "crates/ecs",
    "crates/scheduler",
    "crates/render",
    "crates/platform",
    "crates/math",
    "crates/app",
]
>>>>>>> c05c4c3122a4d3fa6fac94c114ce21c93da93f7a
