[workspace]
resolver = "2"
members = [
    "crates/core",
    "crates/ecs",
    "crates/scheduler",
    "crates/render",
    "crates/platform",
    "crates/math",
    "crates/app",
]
package.version = "0.1.0"
