
[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
core = { path = "../core" }
ecs = { path = "../ecs" }
math = { path = "../math" }
platform = { path = "../platform" }
render = { path = "../render" }
scheduler = { path = "../scheduler" }
winit = "0.30.12"
